const state={agents:[],clusters:{},tasks:[],selected:null,query:'',department:'',task:'',status:'',model:'',integration:'',skill:'',promptCache:{},requestToken:0};
const $=id=>document.getElementById(id);
const arr=v=>Array.isArray(v)?v.filter(Boolean):[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=v=>Array.isArray(v)?v.join(' '):String(v??'');
const clusterTitles={strategie:'Strategie & Führung',kampagne:'Kreativ & Kampagnen',content:'Content & Copy',daten:'Daten & Analytics',kunde:'Research & Kunden',betrieb:'Betrieb & Qualität'};
const taskAgents={strategie:['wilhelm','max','elena','maximilian','branda'],kampagne:['nick','vera','mateo','antonia','berta','branda'],content:['samuel','klara','carl','alex'],daten:['lukas','leo'],kunde:['thomas','karla','karl'],betrieb:['helga','berta','branda','wilhelm']};
const filterDefinitions=[
  ['status','Status','Alle Status'],
  ['model','Modell','Alle Modelle'],
  ['integration','Integration','Alle Integrationen'],
  ['skill','Skill','Alle Skills']
];
function setStatus(message,kind=''){const node=$('appStatus');if(node){node.className=`status-message ${kind}`;node.textContent=message||'';}}
function badge(label,kind=''){return `<span class="badge ${kind}">${esc(label)}</span>`;}
function section(title,value){if(!text(value).trim())return '';return `<section class="detail-section"><div class="detail-label">${esc(title)}</div><div class="detail-value">${esc(text(value))}</div></section>`;}
function listSection(title,value){const values=arr(value);if(!values.length)return '';return `<section class="detail-section"><div class="detail-label">${esc(title)}</div><ul class="detail-list">${values.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section>`;}
function missingSection(title){return section(title,'Nicht öffentlich dokumentiert.');}
function modelOf(agent){return agent.model||'Nicht angegeben';}
function valuesFor(field){const values=new Set();state.agents.forEach(agent=>{if(field==='model'){values.add(modelOf(agent));return;}arr(agent[field]).forEach(value=>values.add(value));});return [...values].sort((a,b)=>a.localeCompare(b,'de'));}
function searchable(agent){return JSON.stringify(agent).toLowerCase();}
function matches(agent){const q=state.query.trim().toLowerCase();const taskOk=!state.task||taskAgents[state.task]?.includes(agent.id);const departmentOk=!state.department||agent.department===state.department;const statusOk=!state.status||agent.status===state.status;const modelOk=!state.model||modelOf(agent)===state.model;const integrationOk=!state.integration||arr(agent.integrations).includes(state.integration);const skillOk=!state.skill||arr(agent.skills).includes(state.skill);return taskOk&&departmentOk&&statusOk&&modelOk&&integrationOk&&skillOk&&(!q||searchable(agent).includes(q));}
function visibleAgents(){return state.agents.filter(matches);}
function renderStats(){$('agentCount').textContent=state.agents.length;$('promptCount').textContent=state.agents.filter(a=>a.promptFile).length;$('configCount').textContent=state.agents.filter(a=>arr(a.skills).length||arr(a.integrations).length).length;$('clusterCount').textContent=Object.keys(state.clusters).length;}
function renderTasks(){$('taskGrid').innerHTML=state.tasks.map(task=>`<button class="task-card ${state.task===task.id?'active':''}" data-task="${esc(task.id)}" aria-pressed="${state.task===task.id}" type="button"><strong>${esc(task.title)}</strong><span>${esc(task.text)}</span></button>`).join('');}
function renderSelect(id,placeholder,values,current){const node=$(id);if(!node)return;node.innerHTML=`<option value="">${esc(placeholder)}</option>`+values.map(value=>`<option value="${esc(value)}" ${current===value?'selected':''}>${esc(value)}</option>`).join('');}
function renderFilters(){const departments=[...new Set(state.agents.map(a=>a.department).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'de'));renderSelect('departmentFilter','Alle Fachbereiche',departments,state.department);filterDefinitions.forEach(([field,,placeholder])=>renderSelect(`${field}Filter`,placeholder,valuesFor(field),state[field]));const filters=[];if(state.query)filters.push(`Suche: ${state.query}`);if(state.department)filters.push(`Fachbereich: ${state.department}`);if(state.task){const task=state.tasks.find(t=>t.id===state.task);if(task)filters.push(`Aufgabe: ${task.title}`);}if(state.status)filters.push(`Status: ${state.status}`);if(state.model)filters.push(`Modell: ${state.model}`);if(state.integration)filters.push(`Integration: ${state.integration}`);if(state.skill)filters.push(`Skill: ${state.skill}`);$('activeFilters').innerHTML=filters.map(filter=>`<span class="active-filter">${esc(filter)}</span>`).join('');}
function renderMap(){const entries=Object.entries(state.clusters);$('mapGrid').innerHTML=entries.map(([cluster,ids])=>`<section class="map-cluster"><div class="cluster-head"><h3>${esc(clusterTitles[cluster]||cluster)}</h3><span>${ids.length}</span></div><div class="map-agents">${ids.map(id=>{const agent=state.agents.find(a=>a.id===id);return agent?`<button class="map-agent ${state.selected===id?'active':''}" data-select="${esc(id)}" type="button"><span class="avatar small">${esc(agent.initials||agent.name.slice(0,1))}</span><span><strong>${esc(agent.name)}</strong><small>${esc(agent.role)}</small></span></button>`:''}).join('')}</div></section>`).join('');}
function renderCards(){const agents=visibleAgents();$('resultStatus').innerHTML=`<strong>${agents.length}</strong> von ${state.agents.length} Agenten`;$('cards').innerHTML=agents.length?agents.map(agent=>`<article class="agent-card ${state.selected===agent.id?'active':''}"><button class="card-main" data-select="${esc(agent.id)}" type="button"><span class="avatar">${esc(agent.initials||agent.name.slice(0,1))}</span><span class="card-copy"><strong>${esc(agent.name)}</strong><span>${esc(agent.role)}</span><small>${esc(agent.shortDescription)}</small></span></button><div class="card-badges">${badge(agent.status||'Status nicht angegeben','status')}${agent.promptFile?badge('Prompt verfügbar','prompt'):badge('Prompt nicht verfügbar','muted')}</div></article>`).join(''):'<div class="empty-results">Keine Agenten passen zu deiner Auswahl.</div>';}
function bindDynamicClicks(){document.querySelectorAll('[data-select]').forEach(button=>{button.onclick=()=>selectAgent(button.dataset.select);});}
function promptBox(agent){if(!agent.promptFile)return missingSection('Prompt');return `<section class="detail-section prompt-section"><div class="prompt-heading"><div><div class="detail-label">Vollständiger Prompt</div><p class="prompt-note">${esc(agent.promptAvailability||'Öffentliche, bereinigte Fassung')}</p></div><button id="copyPrompt" class="copy-button" type="button" disabled>Prompt kopieren</button></div><div id="promptState" class="prompt-state">Prompt wird geladen …</div><textarea id="promptBox" class="prompt-box" readonly aria-label="Vollständiger Prompt"></textarea></section>`;}
function renderDetail(){const agent=state.agents.find(a=>a.id===state.selected);if(!agent){$('detailContent').className='empty';$('detailContent').textContent='Wähle einen Agenten aus der Landkarte oder dem Katalog.';return;}$('detailContent').className='';$('detailContent').innerHTML=`<div class="detail-top"><div class="avatar">${esc(agent.initials||agent.name.slice(0,1))}</div><h2 id="detailTitle" tabindex="-1">${esc(agent.name)}</h2><p class="role">${esc(agent.role)}</p><div class="detail-badges">${badge(agent.status||'Status nicht angegeben','status')}${badge(agent.department||'Abteilung nicht angegeben','department')}${agent.promptFile?badge('Prompt verfügbar','prompt'):badge('Prompt nicht verfügbar','muted')}</div></div><div class="detail-body">${section('Fachbereich & Cluster',`${agent.department||'Abteilung nicht angegeben'} · ${clusterTitles[agent.cluster]||agent.cluster||'Nicht angegeben'}`)}${section('Kurzbeschreibung',agent.shortDescription)}${section('Zweck & Ziel',agent.goal)}${listSection('Typische Aufgaben',agent.useCases)}${listSection('Zielgruppe',agent.audience)}${listSection('Geeignete Eingaben',agent.inputs)}${listSection('Erwartete Ergebnisse',agent.outputs)}${listSection('Grenzen & Ausschlüsse',agent.limitations||agent.limits)}${listSection('Nicht geeignet für',agent.notFor)}${section('Status',agent.status||'Nicht angegeben')}${section('Modell & Einstellungen',agent.model||'Nicht verfügbar')} ${listSection('Skills',agent.skills)}${listSection('Integrationen',agent.integrations)}${agent.actions?listSection('Aktionen',agent.actions):missingSection('Aktionen')}${listSection('Wissensquellen & Dateien',agent.informationSources||agent.files)}${listSection('Vorlagen',agent.templates)}${listSection('Zugeordnete Subagenten',agent.subagents)}${listSection('Offene Punkte',agent.openPoints)}${promptBox(agent)}</div>`;loadPrompt(agent);}
async function loadPrompt(agent){if(!agent.promptFile)return;const box=$('promptBox'),stateNode=$('promptState');if(!box||!stateNode)return;const token=++state.requestToken;try{const response=await fetch(agent.promptFile,{cache:'no-store'});if(!response.ok)throw Error();const prompt=await response.text();if(state.selected!==agent.id||token!==state.requestToken)return;box.value=prompt;state.promptCache[agent.id]=prompt;stateNode.textContent='Prompt geladen.';stateNode.className='prompt-state success';const copy=$('copyPrompt');copy.disabled=false;copy.onclick=async()=>{try{await navigator.clipboard.writeText(prompt);}catch{box.focus();box.select();document.execCommand('copy');}copy.textContent='Kopiert';setTimeout(()=>copy.textContent='Prompt kopieren',1500);};}catch{if(state.selected!==agent.id||token!==state.requestToken)return;stateNode.textContent='Promptdatei nicht vorhanden; die Agentendaten sind trotzdem verfügbar.';stateNode.className='prompt-state error';}}
function updateUrl(id){const url=new URL(window.location.href);if(id)url.searchParams.set('agent',id);else url.searchParams.delete('agent');window.history.replaceState({},'',url);}
function selectAgent(id,updateHistory=true){if(!state.agents.some(agent=>agent.id===id))return;state.selected=id;if(updateHistory)updateUrl(id);renderMap();renderCards();renderDetail();bindDynamicClicks();if(window.innerWidth<980)$('detailPanel').scrollIntoView({behavior:'smooth',block:'start'});}
function renderAll(){renderFilters();renderTasks();renderMap();renderCards();renderDetail();bindDynamicClicks();}
function reset(){state.query='';state.department='';state.task='';state.status='';state.model='';state.integration='';state.skill='';$('searchInput').value='';renderAll();}
function wireFilters(){const map={department:'departmentFilter',status:'statusFilter',model:'modelFilter',integration:'integrationFilter',skill:'skillFilter'};Object.entries(map).forEach(([field,id])=>$(id).addEventListener('change',event=>{state[field]=event.target.value;renderAll();}));$('taskGrid').onclick=event=>{const button=event.target.closest('button[data-task]');if(!button)return;state.task=state.task===button.dataset.task?'':button.dataset.task;renderAll();const catalog=document.querySelector('.catalog');if(catalog)catalog.scrollIntoView({behavior:'smooth',block:'start'});};$('searchInput').oninput=event=>{state.query=event.target.value;renderAll();};$('resetButton').onclick=reset;$('mapToggle').onclick=()=>{const grid=$('mapGrid'),button=$('mapToggle'),collapsed=grid.classList.toggle('collapsed');button.setAttribute('aria-expanded',String(!collapsed));button.textContent=collapsed?'Landkarte ausklappen':'Landkarte einklappen';};}
async function init(){try{const response=await fetch('data/agents.json',{cache:'no-store'});if(!response.ok)throw Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data.agents)||!data.agents.length)throw Error('Keine Agenten gefunden.');state.agents=data.agents;state.tasks=data.tasks||[];state.clusters=state.agents.reduce((groups,agent)=>{(groups[agent.cluster]||(groups[agent.cluster]=[])).push(agent.id);return groups;},{});renderStats();renderAll();wireFilters();const requested=new URLSearchParams(window.location.search).get('agent');if(requested&&state.agents.some(agent=>agent.id===requested))selectAgent(requested,false);setStatus('');}catch(error){setStatus('Die Agenten konnten nicht geladen werden. Bitte Seite neu laden.','error');}}
init();
