const state={agents:[],clusters:{},tasks:[],selected:null,query:'',department:'',task:'',prompts:{}};
const $=id=>document.getElementById(id);
const arr=v=>Array.isArray(v)?v.filter(Boolean):[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=v=>Array.isArray(v)?v.join(' '):String(v??'');
const clusterTitles={strategie:'Strategie & Führung',kampagne:'Kreativ & Kampagnen',content:'Content & Copy',daten:'Daten & Analytics',kunde:'Research & Kunden',betrieb:'Betrieb & Qualität'};
const taskAgents={strategie:['wilhelm','max','elena','maximilian','branda'],kampagne:['nick','vera','mateo','antonia','berta','branda'],content:['samuel','klara','carl','alex'],daten:['lukas','leo'],kunde:['thomas','karla','karl'],betrieb:['helga','berta','branda','wilhelm']};
function setStatus(message,kind=''){const n=$('appStatus');if(n){n.className=`status-message ${kind}`;n.textContent=message||'';}}
function badge(label,kind=''){return `<span class="badge ${kind}">${esc(label)}</span>`;}
function listSection(title,value,source=''){const values=arr(value);if(!values.length)return '';return `<section class="detail-section"><div class="detail-label">${esc(title)}</div><ul class="detail-list">${values.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>${source?`<div class="provenance">${esc(source)}</div>`:''}</section>`;}
function section(title,value,source=''){if(!text(value).trim())return '';return `<section class="detail-section"><div class="detail-label">${esc(title)}</div><div class="detail-value">${esc(text(value))}</div>${source?`<div class="provenance">${esc(source)}</div>`:''}</section>`;}
function visibleAgents(){const q=state.query.trim().toLowerCase();return state.agents.filter(a=>{const hay=JSON.stringify(a).toLowerCase();return(!q||hay.includes(q))&&(!state.department||a.department===state.department)&&(!state.task||taskAgents[state.task]?.includes(a.id));});}
function renderStats(){$('agentCount').textContent=state.agents.length;$('promptCount').textContent=state.agents.filter(a=>a.promptFile).length;$('configCount').textContent=state.agents.filter(a=>arr(a.skills).length||arr(a.integrations).length).length;$('clusterCount').textContent=Object.keys(state.clusters).length;}
function renderTasks(){$('taskGrid').innerHTML=state.tasks.map(t=>`<button class="task-card ${state.task===t.id?'active':''}" data-task="${esc(t.id)}" type="button"><strong>${esc(t.title)}</strong><span>${esc(t.text)}</span></button>`).join('');document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{state.task=state.task===b.dataset.task?'':b.dataset.task;renderAll();});}
function renderMap(){const labels=Object.entries(state.clusters);$('mapGrid').innerHTML=labels.map(([key,ids])=>`<section class="map-cluster"><div class="cluster-head"><h3>${esc(clusterTitles[key]||key)}</h3><span>${ids.length}</span></div><div class="map-agents">${ids.map(id=>{const a=state.agents.find(x=>x.id===id);return a?`<button class="map-agent ${state.selected===id?'active':''}" data-select="${esc(id)}" type="button"><span class="avatar small">${esc(a.initials||a.name[0])}</span><span><strong>${esc(a.name)}</strong><small>${esc(a.role)}</small></span></button>`:''}).join('')}</div></section>`).join('');bindSelects();}
function renderFilters(){const deps=[...new Set(state.agents.map(a=>a.department).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'de'));$('departmentFilter').innerHTML='<option value="">Alle Fachbereiche</option>'+deps.map(d=>`<option value="${esc(d)}" ${d===state.department?'selected':''}>${esc(d)}</option>`).join('');const f=[];if(state.query)f.push(`Suche: ${state.query}`);if(state.department)f.push(`Fachbereich: ${state.department}`);if(state.task){const t=state.tasks.find(x=>x.id===state.task);if(t)f.push(`Aufgabe: ${t.title}`);}$('activeFilters').innerHTML=f.map(x=>`<span class="active-filter">${esc(x)}</span>`).join('');}
function renderCards(){const agents=visibleAgents();$('resultStatus').innerHTML=`<strong>${agents.length}</strong> von ${state.agents.length} Agenten`;$('cards').innerHTML=agents.length?agents.map(a=>`<article class="agent-card ${state.selected===a.id?'active':''}"><button class="card-main" data-select="${esc(a.id)}" type="button"><span class="avatar">${esc(a.initials||a.name[0])}</span><span class="card-copy"><strong>${esc(a.name)}</strong><span>${esc(a.role)}</span><small>${esc(a.shortDescription)}</small></span></button><div class="card-badges">${badge(a.status||'Status nicht angegeben','status')}${a.promptFile?badge('Prompt verfügbar','prompt'):badge('Prompt nicht verfügbar','muted')}</div></article>`).join(''):'<div class="empty-results">Keine Agenten passen zu deiner Auswahl.</div>';bindSelects();}
function bindSelects(){document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>selectAgent(b.dataset.select));}
function renderDetail(){const a=state.agents.find(x=>x.id===state.selected);if(!a){$('detailContent').className='empty';$('detailContent').textContent='Wähle einen Agenten aus der Landkarte oder dem Katalog.';return;}$('detailContent').className='';$('detailContent').innerHTML=`<div class="detail-top"><div class="avatar">${esc(a.initials||a.name[0])}</div><h2 id="detailTitle" tabindex="-1">${esc(a.name)}</h2><p class="role">${esc(a.role)}</p><div class="detail-badges">${badge(a.status||'Status nicht angegeben','status')}${badge(a.department,'department')}${a.promptFile?badge('Prompt verfügbar','prompt'):badge('Prompt nicht verfügbar','muted')}</div></div><div class="detail-body">${section('Fachbereich & Cluster',`${a.department} · ${clusterTitles[a.cluster]||a.cluster}`)}${section('Kurzbeschreibung',a.shortDescription)}${section('Zweck & Ziel',a.goal)}${listSection('Typische Aufgaben',a.useCases)}${listSection('Zielgruppe',a.audience)}${listSection('Geeignete Eingaben',a.inputs)}${listSection('Erwartete Ergebnisse',a.outputs)}${listSection('Grenzen & Ausschlüsse',a.limitations||a.limits)}${listSection('Nicht geeignet für',a.notFor)}${listSection('Skills',a.skills)}${listSection('Integrationen',a.integrations)}${listSection('Wissensquellen & Dateien',a.informationSources||a.files)}${listSection('Vorlagen',a.templates)}${listSection('Zugeordnete Subagenten',a.subagents)}${listSection('Offene Punkte',a.openPoints)}${promptBox(a)}</div>`;loadPrompt(a);}
function promptBox(a){if(!a.promptFile)return section('Prompt','Kein separater öffentlicher Prompt verfügbar.');return `<section class="detail-section prompt-section"><div class="prompt-heading"><div><div class="detail-label">Vollständiger Prompt</div><p class="prompt-note">${esc(a.promptAvailability||'Öffentliche Fassung')}</p></div><button id="copyPrompt" class="copy-button" type="button" disabled>Prompt kopieren</button></div><div id="promptState" class="prompt-state">Prompt wird geladen …</div><textarea id="promptBox" class="prompt-box" readonly></textarea></section>`;}
async function loadPrompt(a){if(!a.promptFile)return;const box=$('promptBox'),statusNode=$('promptState');if(!box||!statusNode)return;try{const r=await fetch(a.promptFile,{cache:'no-store'});if(!r.ok)throw Error();const p=await r.text();if(state.selected!==a.id)return;state.prompts[a.id]=p;box.value=p;statusNode.textContent='Prompt geladen.';statusNode.className='prompt-state success';const copy=$('copyPrompt');copy.disabled=false;copy.onclick=async()=>{try{await navigator.clipboard.writeText(p);}catch{box.focus();box.select();document.execCommand('copy');}copy.textContent='Kopiert';setTimeout(()=>copy.textContent='Prompt kopieren',1500);};}catch{statusNode.textContent='Promptdatei nicht vorhanden; die Agentendaten sind trotzdem verfügbar.';statusNode.className='prompt-state error';}}
function selectAgent(id){if(!state.agents.some(a=>a.id===id))return;state.selected=id;renderMap();renderCards();renderDetail();if(innerWidth<980)$('detailPanel').scrollIntoView({behavior:'smooth'});}
function renderAll(){renderFilters();renderTasks();renderMap();renderCards();renderDetail();}
function reset(){state.query='';state.department='';state.task='';$('searchInput').value='';renderAll();}
async function init(){try{const r=await fetch('data/agents.json',{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const data=await r.json();if(!Array.isArray(data.agents)||data.agents.length===0)throw Error('Keine Agenten gefunden.');state.agents=data.agents;state.tasks=data.tasks||[];state.clusters=state.agents.reduce((g,a)=>{(g[a.cluster]||(g[a.cluster]=[])).push(a.id);return g;},{});renderStats();renderAll();$('searchInput').oninput=e=>{state.query=e.target.value;renderAll();};$('departmentFilter').onchange=e=>{state.department=e.target.value;renderAll();};$('resetButton').onclick=reset;$('mapToggle').onclick=()=>{const g=$('mapGrid'),b=$('mapToggle'),collapsed=g.classList.toggle('collapsed');b.setAttribute('aria-expanded',String(!collapsed));b.textContent=collapsed?'Landkarte ausklappen':'Landkarte einklappen';};setStatus('');}catch(e){setStatus('Die Agenten konnten nicht geladen werden. Bitte Seite neu laden.','error');}}
init();